# -*- coding: utf-8 -*-
"""Sentimental Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgXH5Kxg3USZC6c42wXn8dzV9DvmdJ0m
"""

!pip install -q spotipy
import pandas as pd
import numpy as np
df = pd.read_csv('/content/music_sentiment_dataset.csv').astype({
    'valence_tags': np.float32,
    'arousal_tags': np.float32,
    'dominance_tags': np.float32
})

df.describe(percentiles=[]).round(2)
df.info()

import spotipy
from spotipy import SpotifyException

random_sample = df.dropna(subset=['spotify_id']).sample(1)

track = random_sample['track'].tolist()[0]
artist = random_sample['artist'].tolist()[0]
genre = random_sample['genre'].tolist()[0]
spotify_id = random_sample['spotify_id'].tolist()[0]

print(f'artist: {artist}\ntrack: {track}\ngenre: {genre}\nspotify_id: {spotify_id}')

import json
import spotipy
import webbrowser
from spotipy.oauth2 import SpotifyOAuth

clientID = 'use your spotify client id here'
clientSecret = 'use your spotify client secret here'
redirect_uri = 'http://localhost:8000/callback'

oauth_object = spotipy.SpotifyOAuth(clientID, clientSecret, redirect_uri)
token_dict = oauth_object.get_access_token()
token = token_dict['access_token']
spotifyObject = spotipy.Spotify(auth=token)
user_name = spotifyObject.current_user()

print(json.dumps(user_name, sort_keys=True, indent=4))

search_song = track
results = spotifyObject.search(search_song, 1, 0, "track")
songs_dict = results['tracks']
song_items = songs_dict['items']
song = song_items[0]['external_urls']['spotify']

webbrowser.open(song)
print('Song has opened in your browser.')

import seaborn as sb
import matplotlib.pyplot as plt

sb.jointplot(x='valence_tags', y='dominance_tags', data=df, kind='scatter')
plt.show()

sb.jointplot(x='dominance_tags', y='arousal_tags', data=df, kind='scatter')
plt.show()

sb.jointplot(x='valence_tags', y='arousal_tags', data=df, kind='scatter')
plt.show()

from matplotlib import pyplot as plt
import numpy as np

track = 'Step up'
cars = ['valence_tags', 'arousal_tags', 'dominance_tags']
data = [2.97138, 5.537, 4.726]

fig = plt.figure(figsize=(10, 7))
plt.pie(data, labels=cars)

plt.show()